# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up a virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      - run:
          name: Run YAPF style check on source and test code
          command: |
            . venv/bin/activate
            pip install --upgrade yapf
            yapf --diff --recursive ./src ./tests

      - run:
          name: Run Flake8 linter on source and test code
          command: |
            . venv/bin/activate
            pip install --upgrade flake8
            flake8 ./src ./tests

      - run:
          name: Run the unit tests
          command: |
            . venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: htmlcov
          destination: htmlcov
